### ISSUE TITLE
Request Rating & Review

### ISSUE THREAD

**Issue by ericbhanson** [BoomerangProject/boomerang#8] opened 2018-11-05 20:45 UTC
As a Business, I want to be able to request a rating and review from a Customer so that I can better evaluate my performance and that of my employees.

**Comment by ericbhanson** [comment] 2018-11-05 20:45
Link to feature: https://skedaddle.productboard.com/feature-board/planning/features/1421681

**Comment by Kyrrui** [comment] 2018-11-09 17:38
Working on this now. This will actually be two minorly different features - requesting a business review and requesting a worker review. We will also need designs for a business dashboard

**Comment by ericbhanson** [comment] 2018-11-09 17:49
@Kyrrui do you want two separate issues?

**Comment by Kyrrui** [comment] 2018-11-09 23:02
Yeah, let's do that, because I've also added a verification step so that a business cannot claim a worker until the worker accepts.

**Comment by Kyrrui** [comment] 2018-11-09 23:03
I will close this out, as it is working as intended.

**Closed by Kyrrui** 2018-11-09 23:03 UTC

**Comment by ericbhanson** [comment] 2018-11-09 23:18
Added https://github.com/BoomerangProject/boomerang/issues/13 to cover the request for Worker use case.
